---
title: "Advanced Features"
---

# [Part IV: Advanced Application]{.underline}

-   This part is about exploring complex eco-hydrological scenarios
-   intro to what is covered in the section
-   expected outcome for this section: ability to move from model development to high impact scientific inquiry

# 14 Advanced Features (The Expansion)

-   beyond the baseline
-   moving into specialized simulations

## 14.1 Disturbance modeling

-   disturbance in RHESSys: altering the carbon cycles and redirecting the flow of water and nutrients from the baseline
-   predicting ecosystem resilience and recovery over time

### 14.1.1 Fire Spread and Fire Effects

-   about
-   compiling RHESSys-WMFire: Boost/WMFire library
-   Prerequisites to running the fire model:
    -   Wind speed and direction data
    -   Fire definition file parameters
        -   calculating the fire return interval
        -   calculating wind parameters (EstimateWindDistrExample.R script)
    -   Fire effects parameters in vegetation and soil(patch) definition files
    -   Worldfile header edits
    -   Add worldfile state variable
    -   Command line option
-   Outputs
    -   fire write parameter generated output
    -   spatial level fire outputs and specific fire effects output files
-   stochastic
-   prescribed

### 14.1.2 Land Cover/Vegetation change

-   biomass pool changes
-   drought induced mortality
-   fuel treatments
    -   thinning, controlled burns
-   redefine world functionality (redefine_world\_: multiplier, thin_remain, thin_harvest, thin_snags, thin_harvest)

## 14.2 Multi-scale routing - fine-scale heterogeneity

-   not sure this belongs in advanced features anymore because it has become pretty standard, and I have introduced it above
-   this can be debated!

## 14.3 Target-driven spin-up

-   advanced method of spin-up to reach varying stages of observed ecological states
-   run to reach spatially explicit targets, i.e. LAI
-   types of spin-up targets
-   sources for deriving targets
-   Prerequisites to running:
-   spin-up target file
-   target file header
-   spin-up definition file
-   worldfile with spinup object ID
-   worldfile header pointer
-   command line options

## 14.4 Parallelization (maybe include?)

-   run a large watershed in parallel in order to speed up the simulation process
-   compiling with openmp

# 
