# Preprocessing (The Assembly)
-   the how to section
-   instructions to process/generate files
-   how to format data
-   link to video(s)


## Environmental Setup

-   Standard directory structure
-   naming convention

## Raster Processing

-   Spatial processing using WhiteboxTools and R

## Climate Fles
-   gridded product formatting
    -   ascii format
    -   netcdf format
-   local station data formatting
-   base station

## Definition Files
-   Format - required (ID) and optional parameters
-   Base Files/Default values
-   Parameter file library
-   some parameters may need expanded information, i.e. phenolog flag: static, dynamic, drought

## Generating the Worldfile and Flowtable

### The Template File

-   Format and Initialization
    -   World objects
    -   State variables
    -   Default and base station ID's
-   Required and Optional state variables
-   Editing the template, setting initial conditions

### Aspatial rules file for Multi-scale routing

-   Format
-   Set up for single rule
-   Set up for multiple rules - requires map

### RHESSysPreprocessing R package

-   About
-   Prerequisites: spatial data, template, asp rules file
-   R markdown workflow/script - functions
-   Run the function to generate Worldfile/Flowtable

 
