---
title: "Welcome"
---

# Welcome

## Purpose

-   About the manual, why it exists, what it is for

## Intended Audience

-   Who this is for/Who should be reading this
-   Assumed prerequisite knowledge (i.e. assumes basic knowledge of...provide links to resources where appropriate)
    -   General Modeling
    -   Basic R/Rstudio
    -   GIS and Raster/Vector
    -   Basic Unix/Linux environment (shell, command line, text editor)
    -   Git/GitHub

## Scope

-   What to expect from this book (user will learn....)
-   What the manual covers (practical step-by-step guidance)
-   What it does not cover (underlying theory of the model, all possible functionality)

## Conventions (potentially)

-   How to read this document
-   Key/Legend for document formatting - regarding use of icons, symbols, different font indications

## Manual Structure

-   organization
-   navigation
-   links to sections
-   potentially a link to a quick start guide

## Support/Resources

-   Potentially include author info (Naomi, Janet (contact info?), Ryan)
-   RHESSys GitHub repositories (RHESSys code, RHESSysPreProcessing, RHESSysIOinR, ParameterLibrary)
-   RHESSys Wiki(s)
-   Potentially a FAQ page, a user community forum (i.e. 'issues' section on RHESSys Github repo?)

# 
